// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx8HCl6LOWqUKdgsB8I0nCPcuRGxfmOvk',
    appId: '1:1060189646664:android:780f7266daf574b57e4d7d',
    messagingSenderId: '1060189646664',
    projectId: 'flutter-projects-6a498',
    storageBucket: 'flutter-projects-6a498.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy8txY0EMRcaXJiQyjQRtxKHQM9JGFm_k',
    appId: '1:1060189646664:ios:16e8dcf80d0201917e4d7d',
    messagingSenderId: '1060189646664',
    projectId: 'flutter-projects-6a498',
    storageBucket: 'flutter-projects-6a498.firebasestorage.app',
    iosBundleId: 'com.prueba.push',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy8txY0EMRcaXJiQyjQRtxKHQM9JGFm_k',
    appId: '1:1060189646664:ios:144afe5d447387407e4d7d',
    messagingSenderId: '1060189646664',
    projectId: 'flutter-projects-6a498',
    storageBucket: 'flutter-projects-6a498.firebasestorage.app',
    iosBundleId: 'com.example.push',
  );
}
